# Generated by Django 5.1.1 on 2024-10-01 16:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0002_category_alter_user_id_bids_listings_comments_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listings",
            name="bid",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
